use decoder::{Result, DecodeError};

/// ISO 4271 currency code
#[derive(Clone, Debug, Eq, PartialEq)]
pub enum Currency {
    AED,
    AFN,
    ALL,
    AMD,
    ANG,
    AOA,
    ARS,
    AUD,
    AWG,
    AZN,
    BAM,
    BBD,
    BDT,
    BGN,
    BHD,
    BIF,
    BMD,
    BND,
    BOB,
    BRL,
    BSD,
    BTN,
    BWP,
    BYR,
    BZD,
    CAD,
    CDF,
    CHF,
    CLP,
    CNY,
    COP,
    CRC,
    CUC,
    CUP,
    CVE,
    CZK,
    DJF,
    DKK,
    DOP,
    DZD,
    EGP,
    ERN,
    ETB,
    EUR,
    FJD,
    FKP,
    GBP,
    GEL,
    GGP,
    GHS,
    GIP,
    GMD,
    GNF,
    GTQ,
    GYD,
    HKD,
    HNL,
    HRK,
    HTG,
    HUF,
    IDR,
    ILS,
    IMP,
    INR,
    IQD,
    IRR,
    ISK,
    JEP,
    JMD,
    JOD,
    JPY,
    KES,
    KGS,
    KHR,
    KMF,
    KPW,
    KRW,
    KWD,
    KYD,
    KZT,
    LAK,
    LBP,
    LKR,
    LRD,
    LSL,
    LYD,
    MAD,
    MDL,
    MGA,
    MKD,
    MMK,
    MNT,
    MOP,
    MRO,
    MUR,
    MVR,
    MWK,
    MXN,
    MYR,
    MZN,
    NAD,
    NGN,
    NIO,
    NOK,
    NPR,
    NZD,
    OMR,
    PAB,
    PEN,
    PGK,
    PHP,
    PKR,
    PLN,
    PYG,
    QAR,
    RON,
    RSD,
    RUB,
    RWF,
    SAR,
    SBD,
    SCR,
    SDG,
    SEK,
    SGD,
    SHP,
    SLL,
    SOS,
    SPL,
    SRD,
    STD,
    SVC,
    SYP,
    SZL,
    THB,
    TJS,
    TMT,
    TND,
    TOP,
    TRY,
    TTD,
    TVD,
    TWD,
    TZS,
    UAH,
    UGX,
    USD,
    UYU,
    UZS,
    VEF,
    VND,
    VUV,
    WST,
    XAF,
    XCD,
    XDR,
    XOF,
    XPF,
    YER,
    ZAR,
    ZMW,
    ZWD,
}


pub fn decode_currency(msg: &[u8; 3]) -> Result<Currency> {
    match msg {
        b"AED" => Ok(Currency::AED),
        b"AFN" => Ok(Currency::AFN),
        b"ALL" => Ok(Currency::ALL),
        b"AMD" => Ok(Currency::AMD),
        b"ANG" => Ok(Currency::ANG),
        b"AOA" => Ok(Currency::AOA),
        b"ARS" => Ok(Currency::ARS),
        b"AUD" => Ok(Currency::AUD),
        b"AWG" => Ok(Currency::AWG),
        b"AZN" => Ok(Currency::AZN),
        b"BAM" => Ok(Currency::BAM),
        b"BBD" => Ok(Currency::BBD),
        b"BDT" => Ok(Currency::BDT),
        b"BGN" => Ok(Currency::BGN),
        b"BHD" => Ok(Currency::BHD),
        b"BIF" => Ok(Currency::BIF),
        b"BMD" => Ok(Currency::BMD),
        b"BND" => Ok(Currency::BND),
        b"BOB" => Ok(Currency::BOB),
        b"BRL" => Ok(Currency::BRL),
        b"BSD" => Ok(Currency::BSD),
        b"BTN" => Ok(Currency::BTN),
        b"BWP" => Ok(Currency::BWP),
        b"BYR" => Ok(Currency::BYR),
        b"BZD" => Ok(Currency::BZD),
        b"CAD" => Ok(Currency::CAD),
        b"CDF" => Ok(Currency::CDF),
        b"CHF" => Ok(Currency::CHF),
        b"CLP" => Ok(Currency::CLP),
        b"CNY" => Ok(Currency::CNY),
        b"COP" => Ok(Currency::COP),
        b"CRC" => Ok(Currency::CRC),
        b"CUC" => Ok(Currency::CUC),
        b"CUP" => Ok(Currency::CUP),
        b"CVE" => Ok(Currency::CVE),
        b"CZK" => Ok(Currency::CZK),
        b"DJF" => Ok(Currency::DJF),
        b"DKK" => Ok(Currency::DKK),
        b"DOP" => Ok(Currency::DOP),
        b"DZD" => Ok(Currency::DZD),
        b"EGP" => Ok(Currency::EGP),
        b"ERN" => Ok(Currency::ERN),
        b"ETB" => Ok(Currency::ETB),
        b"EUR" => Ok(Currency::EUR),
        b"FJD" => Ok(Currency::FJD),
        b"FKP" => Ok(Currency::FKP),
        b"GBP" => Ok(Currency::GBP),
        b"GEL" => Ok(Currency::GEL),
        b"GGP" => Ok(Currency::GGP),
        b"GHS" => Ok(Currency::GHS),
        b"GIP" => Ok(Currency::GIP),
        b"GMD" => Ok(Currency::GMD),
        b"GNF" => Ok(Currency::GNF),
        b"GTQ" => Ok(Currency::GTQ),
        b"GYD" => Ok(Currency::GYD),
        b"HKD" => Ok(Currency::HKD),
        b"HNL" => Ok(Currency::HNL),
        b"HRK" => Ok(Currency::HRK),
        b"HTG" => Ok(Currency::HTG),
        b"HUF" => Ok(Currency::HUF),
        b"IDR" => Ok(Currency::IDR),
        b"ILS" => Ok(Currency::ILS),
        b"IMP" => Ok(Currency::IMP),
        b"INR" => Ok(Currency::INR),
        b"IQD" => Ok(Currency::IQD),
        b"IRR" => Ok(Currency::IRR),
        b"ISK" => Ok(Currency::ISK),
        b"JEP" => Ok(Currency::JEP),
        b"JMD" => Ok(Currency::JMD),
        b"JOD" => Ok(Currency::JOD),
        b"JPY" => Ok(Currency::JPY),
        b"KES" => Ok(Currency::KES),
        b"KGS" => Ok(Currency::KGS),
        b"KHR" => Ok(Currency::KHR),
        b"KMF" => Ok(Currency::KMF),
        b"KPW" => Ok(Currency::KPW),
        b"KRW" => Ok(Currency::KRW),
        b"KWD" => Ok(Currency::KWD),
        b"KYD" => Ok(Currency::KYD),
        b"KZT" => Ok(Currency::KZT),
        b"LAK" => Ok(Currency::LAK),
        b"LBP" => Ok(Currency::LBP),
        b"LKR" => Ok(Currency::LKR),
        b"LRD" => Ok(Currency::LRD),
        b"LSL" => Ok(Currency::LSL),
        b"LYD" => Ok(Currency::LYD),
        b"MAD" => Ok(Currency::MAD),
        b"MDL" => Ok(Currency::MDL),
        b"MGA" => Ok(Currency::MGA),
        b"MKD" => Ok(Currency::MKD),
        b"MMK" => Ok(Currency::MMK),
        b"MNT" => Ok(Currency::MNT),
        b"MOP" => Ok(Currency::MOP),
        b"MRO" => Ok(Currency::MRO),
        b"MUR" => Ok(Currency::MUR),
        b"MVR" => Ok(Currency::MVR),
        b"MWK" => Ok(Currency::MWK),
        b"MXN" => Ok(Currency::MXN),
        b"MYR" => Ok(Currency::MYR),
        b"MZN" => Ok(Currency::MZN),
        b"NAD" => Ok(Currency::NAD),
        b"NGN" => Ok(Currency::NGN),
        b"NIO" => Ok(Currency::NIO),
        b"NOK" => Ok(Currency::NOK),
        b"NPR" => Ok(Currency::NPR),
        b"NZD" => Ok(Currency::NZD),
        b"OMR" => Ok(Currency::OMR),
        b"PAB" => Ok(Currency::PAB),
        b"PEN" => Ok(Currency::PEN),
        b"PGK" => Ok(Currency::PGK),
        b"PHP" => Ok(Currency::PHP),
        b"PKR" => Ok(Currency::PKR),
        b"PLN" => Ok(Currency::PLN),
        b"PYG" => Ok(Currency::PYG),
        b"QAR" => Ok(Currency::QAR),
        b"RON" => Ok(Currency::RON),
        b"RSD" => Ok(Currency::RSD),
        b"RUB" => Ok(Currency::RUB),
        b"RWF" => Ok(Currency::RWF),
        b"SAR" => Ok(Currency::SAR),
        b"SBD" => Ok(Currency::SBD),
        b"SCR" => Ok(Currency::SCR),
        b"SDG" => Ok(Currency::SDG),
        b"SEK" => Ok(Currency::SEK),
        b"SGD" => Ok(Currency::SGD),
        b"SHP" => Ok(Currency::SHP),
        b"SLL" => Ok(Currency::SLL),
        b"SOS" => Ok(Currency::SOS),
        b"SPL" => Ok(Currency::SPL),
        b"SRD" => Ok(Currency::SRD),
        b"STD" => Ok(Currency::STD),
        b"SVC" => Ok(Currency::SVC),
        b"SYP" => Ok(Currency::SYP),
        b"SZL" => Ok(Currency::SZL),
        b"THB" => Ok(Currency::THB),
        b"TJS" => Ok(Currency::TJS),
        b"TMT" => Ok(Currency::TMT),
        b"TND" => Ok(Currency::TND),
        b"TOP" => Ok(Currency::TOP),
        b"TRY" => Ok(Currency::TRY),
        b"TTD" => Ok(Currency::TTD),
        b"TVD" => Ok(Currency::TVD),
        b"TWD" => Ok(Currency::TWD),
        b"TZS" => Ok(Currency::TZS),
        b"UAH" => Ok(Currency::UAH),
        b"UGX" => Ok(Currency::UGX),
        b"USD" => Ok(Currency::USD),
        b"UYU" => Ok(Currency::UYU),
        b"UZS" => Ok(Currency::UZS),
        b"VEF" => Ok(Currency::VEF),
        b"VND" => Ok(Currency::VND),
        b"VUV" => Ok(Currency::VUV),
        b"WST" => Ok(Currency::WST),
        b"XAF" => Ok(Currency::XAF),
        b"XCD" => Ok(Currency::XCD),
        b"XDR" => Ok(Currency::XDR),
        b"XOF" => Ok(Currency::XOF),
        b"XPF" => Ok(Currency::XPF),
        b"YER" => Ok(Currency::YER),
        b"ZAR" => Ok(Currency::ZAR),
        b"ZMW" => Ok(Currency::ZMW),
        b"ZWD" => Ok(Currency::ZWD),
        _ => Err(DecodeError::Overflow)
    }
}

pub fn encode_currency(c: Currency) -> [u8; 3] {
    match c {
        Currency::AED => *b"AED",
        Currency::AFN => *b"AFN",
        Currency::ALL => *b"ALL",
        Currency::AMD => *b"AMD",
        Currency::ANG => *b"ANG",
        Currency::AOA => *b"AOA",
        Currency::ARS => *b"ARS",
        Currency::AUD => *b"AUD",
        Currency::AWG => *b"AWG",
        Currency::AZN => *b"AZN",
        Currency::BAM => *b"BAM",
        Currency::BBD => *b"BBD",
        Currency::BDT => *b"BDT",
        Currency::BGN => *b"BGN",
        Currency::BHD => *b"BHD",
        Currency::BIF => *b"BIF",
        Currency::BMD => *b"BMD",
        Currency::BND => *b"BND",
        Currency::BOB => *b"BOB",
        Currency::BRL => *b"BRL",
        Currency::BSD => *b"BSD",
        Currency::BTN => *b"BTN",
        Currency::BWP => *b"BWP",
        Currency::BYR => *b"BYR",
        Currency::BZD => *b"BZD",
        Currency::CAD => *b"CAD",
        Currency::CDF => *b"CDF",
        Currency::CHF => *b"CHF",
        Currency::CLP => *b"CLP",
        Currency::CNY => *b"CNY",
        Currency::COP => *b"COP",
        Currency::CRC => *b"CRC",
        Currency::CUC => *b"CUC",
        Currency::CUP => *b"CUP",
        Currency::CVE => *b"CVE",
        Currency::CZK => *b"CZK",
        Currency::DJF => *b"DJF",
        Currency::DKK => *b"DKK",
        Currency::DOP => *b"DOP",
        Currency::DZD => *b"DZD",
        Currency::EGP => *b"EGP",
        Currency::ERN => *b"ERN",
        Currency::ETB => *b"ETB",
        Currency::EUR => *b"EUR",
        Currency::FJD => *b"FJD",
        Currency::FKP => *b"FKP",
        Currency::GBP => *b"GBP",
        Currency::GEL => *b"GEL",
        Currency::GGP => *b"GGP",
        Currency::GHS => *b"GHS",
        Currency::GIP => *b"GIP",
        Currency::GMD => *b"GMD",
        Currency::GNF => *b"GNF",
        Currency::GTQ => *b"GTQ",
        Currency::GYD => *b"GYD",
        Currency::HKD => *b"HKD",
        Currency::HNL => *b"HNL",
        Currency::HRK => *b"HRK",
        Currency::HTG => *b"HTG",
        Currency::HUF => *b"HUF",
        Currency::IDR => *b"IDR",
        Currency::ILS => *b"ILS",
        Currency::IMP => *b"IMP",
        Currency::INR => *b"INR",
        Currency::IQD => *b"IQD",
        Currency::IRR => *b"IRR",
        Currency::ISK => *b"ISK",
        Currency::JEP => *b"JEP",
        Currency::JMD => *b"JMD",
        Currency::JOD => *b"JOD",
        Currency::JPY => *b"JPY",
        Currency::KES => *b"KES",
        Currency::KGS => *b"KGS",
        Currency::KHR => *b"KHR",
        Currency::KMF => *b"KMF",
        Currency::KPW => *b"KPW",
        Currency::KRW => *b"KRW",
        Currency::KWD => *b"KWD",
        Currency::KYD => *b"KYD",
        Currency::KZT => *b"KZT",
        Currency::LAK => *b"LAK",
        Currency::LBP => *b"LBP",
        Currency::LKR => *b"LKR",
        Currency::LRD => *b"LRD",
        Currency::LSL => *b"LSL",
        Currency::LYD => *b"LYD",
        Currency::MAD => *b"MAD",
        Currency::MDL => *b"MDL",
        Currency::MGA => *b"MGA",
        Currency::MKD => *b"MKD",
        Currency::MMK => *b"MMK",
        Currency::MNT => *b"MNT",
        Currency::MOP => *b"MOP",
        Currency::MRO => *b"MRO",
        Currency::MUR => *b"MUR",
        Currency::MVR => *b"MVR",
        Currency::MWK => *b"MWK",
        Currency::MXN => *b"MXN",
        Currency::MYR => *b"MYR",
        Currency::MZN => *b"MZN",
        Currency::NAD => *b"NAD",
        Currency::NGN => *b"NGN",
        Currency::NIO => *b"NIO",
        Currency::NOK => *b"NOK",
        Currency::NPR => *b"NPR",
        Currency::NZD => *b"NZD",
        Currency::OMR => *b"OMR",
        Currency::PAB => *b"PAB",
        Currency::PEN => *b"PEN",
        Currency::PGK => *b"PGK",
        Currency::PHP => *b"PHP",
        Currency::PKR => *b"PKR",
        Currency::PLN => *b"PLN",
        Currency::PYG => *b"PYG",
        Currency::QAR => *b"QAR",
        Currency::RON => *b"RON",
        Currency::RSD => *b"RSD",
        Currency::RUB => *b"RUB",
        Currency::RWF => *b"RWF",
        Currency::SAR => *b"SAR",
        Currency::SBD => *b"SBD",
        Currency::SCR => *b"SCR",
        Currency::SDG => *b"SDG",
        Currency::SEK => *b"SEK",
        Currency::SGD => *b"SGD",
        Currency::SHP => *b"SHP",
        Currency::SLL => *b"SLL",
        Currency::SOS => *b"SOS",
        Currency::SPL => *b"SPL",
        Currency::SRD => *b"SRD",
        Currency::STD => *b"STD",
        Currency::SVC => *b"SVC",
        Currency::SYP => *b"SYP",
        Currency::SZL => *b"SZL",
        Currency::THB => *b"THB",
        Currency::TJS => *b"TJS",
        Currency::TMT => *b"TMT",
        Currency::TND => *b"TND",
        Currency::TOP => *b"TOP",
        Currency::TRY => *b"TRY",
        Currency::TTD => *b"TTD",
        Currency::TVD => *b"TVD",
        Currency::TWD => *b"TWD",
        Currency::TZS => *b"TZS",
        Currency::UAH => *b"UAH",
        Currency::UGX => *b"UGX",
        Currency::USD => *b"USD",
        Currency::UYU => *b"UYU",
        Currency::UZS => *b"UZS",
        Currency::VEF => *b"VEF",
        Currency::VND => *b"VND",
        Currency::VUV => *b"VUV",
        Currency::WST => *b"WST",
        Currency::XAF => *b"XAF",
        Currency::XCD => *b"XCD",
        Currency::XDR => *b"XDR",
        Currency::XOF => *b"XOF",
        Currency::XPF => *b"XPF",
        Currency::YER => *b"YER",
        Currency::ZAR => *b"ZAR",
        Currency::ZMW => *b"ZMW",
        Currency::ZWD => *b"ZWD",
    }
}


#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_decode_currency() {
        assert_eq!(decode_currency(b"USD").unwrap(), Currency::USD);
        assert!(decode_currency(b"USX").is_err());
    }

    #[test]
    fn test_encode_currency() {
        assert_eq!(&encode_currency(Currency::USD), b"USD");
        assert_eq!(&encode_currency(Currency::CAD), b"CAD");
    }
}
