use types::*;
use fix41::fields::*;

pub struct Header {
    pub begin_string: FIXString,
    pub body_length: FIXInt,
    pub msg_type: MsgType,
    pub sender_comp_id: FIXString,
    pub target_comp_id: FIXString,
    pub on_behalf_of_comp_id: Option<FIXString>,
    pub deliver_to_comp_id: Option<FIXString>,
    pub secure_data_len: Option<Length>,
    pub secure_data: Option<Data>,
    pub msg_seq_num: FIXInt,
    pub sender_sub_id: Option<FIXString>,
    pub sender_location_id: Option<FIXString>,
    pub target_sub_id: Option<FIXString>,
    pub target_location_id: Option<FIXString>,
    pub on_behalf_of_sub_id: Option<FIXString>,
    pub on_behalf_of_location_id: Option<FIXString>,
    pub deliver_to_sub_id: Option<FIXString>,
    pub deliver_to_location_id: Option<FIXString>,
    pub poss_dup_flag: Option<PossDupFlag>,
    pub poss_resend: Option<PossResend>,
    pub sending_time: UTCTimeOnly,
    pub orig_sending_time: Option<UTCTimeOnly>
}

pub struct Message {
    /// Standard message header.
    pub header: Header,
    /// Message body
    pub body: MessageBody,
}

pub enum MessageBody {
    /// Heartbeat message. Message code: 0
    Heartbeat {
        test_req_id: Option<FIXString>
    },

    /// TestRequest message. Message code: 1
    TestRequest {
        test_req_id: FIXString
    },

    /// ResendRequest message. Message code: 2
    ResendRequest {
        begin_seq_no: FIXInt,
        end_seq_no: FIXInt
    },

    /// Reject message. Message code: 3
    Reject {
        ref_seq_num: FIXInt,
        text: Option<FIXString>
    },

    /// SequenceReset message. Message code: 4
    SequenceReset {
        gap_fill_flag: Option<GapFillFlag>,
        new_seq_no: FIXInt
    },

    /// Logout message. Message code: 5
    Logout {
        text: Option<FIXString>
    },

    /// IOI message. Message code: 6
    IOI {
        io_iid: FIXString,
        ioi_trans_type: IOITransType,
        ioi_ref_id: Option<FIXString>,
        symbol: FIXString,
        symbol_sfx: Option<FIXString>,
        security_id: Option<FIXString>,
        id_source: Option<IDSource>,
        security_type: Option<SecurityType>,
        maturity_month_year: Option<MonthYear>,
        maturity_day: Option<DayOfMonth>,
        put_or_call: Option<PutOrCall>,
        strike_price: Option<FIXFloat>,
        opt_attribute: Option<FIXString>,
        security_exchange: Option<FIXString>,
        issuer: Option<FIXString>,
        security_desc: Option<FIXString>,
        side: Side,
        ioi_shares: IOIShares,
        price: Option<FIXFloat>,
        currency: Option<FIXString>,
        valid_until_time: Option<UTCTimeOnly>,
        ioi_qlty_ind: Option<IOIQltyInd>,
        ioi_oth_svc: Option<IOIOthSvc>,
        ioi_natural_flag: Option<IOINaturalFlag>,
        ioi_qualifier: Option<IOIQualifier>,
        text: Option<FIXString>,
        transact_time: Option<UTCTimeOnly>,
        url_link: Option<FIXString>
    },

    /// Advertisement message. Message code: 7
    Advertisement {
        adv_id: FIXString,
        adv_trans_type: AdvTransType,
        adv_ref_id: Option<FIXString>,
        symbol: FIXString,
        symbol_sfx: Option<FIXString>,
        security_id: Option<FIXString>,
        id_source: Option<IDSource>,
        security_type: Option<SecurityType>,
        maturity_month_year: Option<MonthYear>,
        maturity_day: Option<DayOfMonth>,
        put_or_call: Option<PutOrCall>,
        strike_price: Option<FIXFloat>,
        opt_attribute: Option<FIXString>,
        security_exchange: Option<FIXString>,
        issuer: Option<FIXString>,
        security_desc: Option<FIXString>,
        adv_side: AdvSide,
        shares: FIXInt,
        price: Option<FIXFloat>,
        currency: Option<FIXString>,
        trade_date: Option<UTCDateOnly>,
        transact_time: Option<UTCTimeOnly>,
        text: Option<FIXString>,
        url_link: Option<FIXString>,
        last_mkt: Option<FIXString>
    },

    /// ExecutionReport message. Message code: 8
    ExecutionReport {
        order_id: FIXString,
        secondary_order_id: Option<FIXString>,
        cl_ord_id: Option<FIXString>,
        orig_cl_ord_id: Option<FIXString>,
        client_id: Option<FIXString>,
        exec_broker: Option<FIXString>,
        list_id: Option<FIXString>,
        exec_id: FIXString,
        exec_trans_type: ExecTransType,
        exec_ref_id: Option<FIXString>,
        exec_type: ExecType,
        ord_status: OrdStatus,
        ord_rej_reason: Option<OrdRejReason>,
        account: Option<FIXString>,
        settlmnt_typ: Option<SettlmntTyp>,
        fut_sett_date: Option<UTCDateOnly>,
        symbol: FIXString,
        symbol_sfx: Option<FIXString>,
        security_id: Option<FIXString>,
        id_source: Option<IDSource>,
        security_type: Option<SecurityType>,
        maturity_month_year: Option<MonthYear>,
        maturity_day: Option<DayOfMonth>,
        put_or_call: Option<PutOrCall>,
        strike_price: Option<FIXFloat>,
        opt_attribute: Option<FIXString>,
        security_exchange: Option<FIXString>,
        issuer: Option<FIXString>,
        security_desc: Option<FIXString>,
        side: Side,
        order_qty: FIXInt,
        ord_type: Option<OrdType>,
        price: Option<FIXFloat>,
        stop_px: Option<FIXFloat>,
        peg_difference: Option<FIXFloat>,
        currency: Option<FIXString>,
        time_in_force: Option<TimeInForce>,
        expire_time: Option<UTCTimeOnly>,
        exec_inst: Option<ExecInst>,
        rule80_a: Option<Rule80A>,
        last_shares: FIXInt,
        last_px: FIXFloat,
        last_spot_rate: Option<FIXFloat>,
        last_forward_points: Option<FIXFloat>,
        last_mkt: Option<FIXString>,
        last_capacity: Option<LastCapacity>,
        leaves_qty: FIXInt,
        cum_qty: FIXInt,
        avg_px: FIXFloat,
        trade_date: Option<UTCDateOnly>,
        transact_time: Option<UTCTimeOnly>,
        report_to_exch: Option<ReportToExch>,
        commission: Option<FIXFloat>,
        comm_type: Option<CommType>,
        settl_curr_amt: Option<FIXFloat>,
        settl_currency: Option<FIXString>,
        settl_curr_fx_rate: Option<FIXFloat>,
        settl_curr_fx_rate_calc: Option<SettlCurrFxRateCalc>,
        text: Option<FIXString>
    },

    /// OrderCancelReject message. Message code: 9
    OrderCancelReject {
        order_id: FIXString,
        secondary_order_id: Option<FIXString>,
        cl_ord_id: FIXString,
        orig_cl_ord_id: FIXString,
        ord_status: OrdStatus,
        client_id: Option<FIXString>,
        exec_broker: Option<FIXString>,
        list_id: Option<FIXString>,
        cxl_rej_reason: Option<CxlRejReason>,
        text: Option<FIXString>
    },

    /// Logon message. Message code: A
    Logon {
        encrypt_method: EncryptMethod,
        heart_bt_int: FIXInt,
        raw_data_length: Option<Length>,
        raw_data: Option<Data>,
        reset_seq_num_flag: Option<ResetSeqNumFlag>
    },

    /// News message. Message code: B
    News {
        orig_time: Option<UTCTimeOnly>,
        urgency: Option<Urgency>,
        headline: FIXString,
        relatd_sym: Option<FIXString>,
        symbol_sfx: Option<FIXString>,
        security_id: Option<FIXString>,
        id_source: Option<IDSource>,
        security_type: Option<SecurityType>,
        maturity_month_year: Option<MonthYear>,
        maturity_day: Option<DayOfMonth>,
        put_or_call: Option<PutOrCall>,
        strike_price: Option<FIXFloat>,
        opt_attribute: Option<FIXString>,
        security_exchange: Option<FIXString>,
        issuer: Option<FIXString>,
        security_desc: Option<FIXString>,
        text: FIXString,
        url_link: Option<FIXString>,
        raw_data_length: Option<Length>,
        raw_data: Option<Data>
    },

    /// Email message. Message code: C
    Email {
        email_thread_id: FIXString,
        email_type: EmailType,
        orig_time: Option<UTCTimeOnly>,
        subject: FIXString,
        relatd_sym: Option<FIXString>,
        symbol_sfx: Option<FIXString>,
        security_id: Option<FIXString>,
        id_source: Option<IDSource>,
        security_type: Option<SecurityType>,
        maturity_month_year: Option<MonthYear>,
        maturity_day: Option<DayOfMonth>,
        put_or_call: Option<PutOrCall>,
        strike_price: Option<FIXFloat>,
        opt_attribute: Option<FIXString>,
        security_exchange: Option<FIXString>,
        issuer: Option<FIXString>,
        security_desc: Option<FIXString>,
        order_id: Option<FIXString>,
        cl_ord_id: Option<FIXString>,
        text: FIXString,
        raw_data_length: Option<Length>,
        raw_data: Option<Data>
    },

    /// NewOrderSingle message. Message code: D
    NewOrderSingle {
        cl_ord_id: FIXString,
        client_id: Option<FIXString>,
        exec_broker: Option<FIXString>,
        account: Option<FIXString>,
        settlmnt_typ: Option<SettlmntTyp>,
        fut_sett_date: Option<UTCDateOnly>,
        handl_inst: HandlInst,
        exec_inst: Option<ExecInst>,
        min_qty: Option<FIXInt>,
        max_floor: Option<FIXInt>,
        ex_destination: Option<FIXString>,
        process_code: Option<ProcessCode>,
        symbol: FIXString,
        symbol_sfx: Option<FIXString>,
        security_id: Option<FIXString>,
        id_source: Option<IDSource>,
        security_type: Option<SecurityType>,
        maturity_month_year: Option<MonthYear>,
        maturity_day: Option<DayOfMonth>,
        put_or_call: Option<PutOrCall>,
        strike_price: Option<FIXFloat>,
        opt_attribute: Option<FIXString>,
        security_exchange: Option<FIXString>,
        issuer: Option<FIXString>,
        security_desc: Option<FIXString>,
        prev_close_px: Option<FIXFloat>,
        side: Side,
        locate_reqd: Option<LocateReqd>,
        order_qty: Option<FIXInt>,
        cash_order_qty: Option<FIXFloat>,
        ord_type: OrdType,
        price: Option<FIXFloat>,
        stop_px: Option<FIXFloat>,
        currency: Option<FIXString>,
        io_iid: Option<FIXString>,
        quote_id: Option<FIXString>,
        time_in_force: Option<TimeInForce>,
        expire_time: Option<UTCTimeOnly>,
        commission: Option<FIXFloat>,
        comm_type: Option<CommType>,
        rule80_a: Option<Rule80A>,
        forex_req: Option<ForexReq>,
        settl_currency: Option<FIXString>,
        text: Option<FIXString>,
        fut_sett_date2: Option<UTCDateOnly>,
        order_qty2: Option<FIXFloat>,
        open_close: Option<OpenClose>,
        covered_or_uncovered: Option<CoveredOrUncovered>,
        customer_or_firm: Option<CustomerOrFirm>,
        max_show: Option<FIXInt>,
        peg_difference: Option<FIXFloat>
    },

    /// NewOrderList message. Message code: E
    NewOrderList {
        list_id: FIXString,
        wave_no: Option<FIXString>,
        list_seq_no: FIXInt,
        list_no_ords: FIXInt,
        list_exec_inst: Option<FIXString>,
        cl_ord_id: FIXString,
        client_id: Option<FIXString>,
        exec_broker: Option<FIXString>,
        account: Option<FIXString>,
        settlmnt_typ: Option<SettlmntTyp>,
        fut_sett_date: Option<UTCDateOnly>,
        handl_inst: HandlInst,
        exec_inst: Option<ExecInst>,
        min_qty: Option<FIXInt>,
        max_floor: Option<FIXInt>,
        ex_destination: Option<FIXString>,
        process_code: Option<ProcessCode>,
        symbol: FIXString,
        symbol_sfx: Option<FIXString>,
        security_id: Option<FIXString>,
        id_source: Option<IDSource>,
        security_type: Option<SecurityType>,
        maturity_month_year: Option<MonthYear>,
        maturity_day: Option<DayOfMonth>,
        put_or_call: Option<PutOrCall>,
        strike_price: Option<FIXFloat>,
        opt_attribute: Option<FIXString>,
        security_exchange: Option<FIXString>,
        issuer: Option<FIXString>,
        security_desc: Option<FIXString>,
        prev_close_px: Option<FIXFloat>,
        side: Side,
        locate_reqd: Option<LocateReqd>,
        order_qty: FIXInt,
        ord_type: OrdType,
        price: Option<FIXFloat>,
        stop_px: Option<FIXFloat>,
        peg_difference: Option<FIXFloat>,
        currency: Option<FIXString>,
        time_in_force: Option<TimeInForce>,
        expire_time: Option<UTCTimeOnly>,
        commission: Option<FIXFloat>,
        comm_type: Option<CommType>,
        rule80_a: Option<Rule80A>,
        forex_req: Option<ForexReq>,
        settl_currency: Option<FIXString>,
        text: Option<FIXString>,
        fut_sett_date2: Option<UTCDateOnly>,
        order_qty2: Option<FIXFloat>,
        open_close: Option<OpenClose>,
        covered_or_uncovered: Option<CoveredOrUncovered>,
        customer_or_firm: Option<CustomerOrFirm>,
        max_show: Option<FIXInt>
    },

    /// OrderCancelRequest message. Message code: F
    OrderCancelRequest {
        orig_cl_ord_id: FIXString,
        order_id: Option<FIXString>,
        cl_ord_id: FIXString,
        list_id: Option<FIXString>,
        client_id: Option<FIXString>,
        exec_broker: Option<FIXString>,
        symbol: FIXString,
        symbol_sfx: Option<FIXString>,
        security_id: Option<FIXString>,
        id_source: Option<IDSource>,
        security_type: Option<SecurityType>,
        maturity_month_year: Option<MonthYear>,
        maturity_day: Option<DayOfMonth>,
        put_or_call: Option<PutOrCall>,
        strike_price: Option<FIXFloat>,
        opt_attribute: Option<FIXString>,
        security_exchange: Option<FIXString>,
        issuer: Option<FIXString>,
        security_desc: Option<FIXString>,
        side: Side,
        order_qty: Option<FIXInt>,
        cash_order_qty: Option<FIXFloat>,
        text: Option<FIXString>
    },

    /// OrderCancelReplaceRequest message. Message code: G
    OrderCancelReplaceRequest {
        order_id: Option<FIXString>,
        client_id: Option<FIXString>,
        exec_broker: Option<FIXString>,
        orig_cl_ord_id: FIXString,
        cl_ord_id: FIXString,
        list_id: Option<FIXString>,
        account: Option<FIXString>,
        settlmnt_typ: Option<SettlmntTyp>,
        fut_sett_date: Option<UTCDateOnly>,
        handl_inst: HandlInst,
        exec_inst: Option<ExecInst>,
        min_qty: Option<FIXInt>,
        max_floor: Option<FIXInt>,
        ex_destination: Option<FIXString>,
        symbol: FIXString,
        symbol_sfx: Option<FIXString>,
        security_id: Option<FIXString>,
        id_source: Option<IDSource>,
        security_type: Option<SecurityType>,
        maturity_month_year: Option<MonthYear>,
        maturity_day: Option<DayOfMonth>,
        put_or_call: Option<PutOrCall>,
        strike_price: Option<FIXFloat>,
        opt_attribute: Option<FIXString>,
        security_exchange: Option<FIXString>,
        issuer: Option<FIXString>,
        security_desc: Option<FIXString>,
        side: Side,
        order_qty: Option<FIXInt>,
        cash_order_qty: Option<FIXFloat>,
        ord_type: OrdType,
        price: Option<FIXFloat>,
        stop_px: Option<FIXFloat>,
        peg_difference: Option<FIXFloat>,
        currency: Option<FIXString>,
        time_in_force: Option<TimeInForce>,
        expire_time: Option<UTCTimeOnly>,
        commission: Option<FIXFloat>,
        comm_type: Option<CommType>,
        rule80_a: Option<Rule80A>,
        forex_req: Option<ForexReq>,
        settl_currency: Option<FIXString>,
        text: Option<FIXString>,
        fut_sett_date2: Option<UTCDateOnly>,
        order_qty2: Option<FIXFloat>,
        open_close: Option<OpenClose>,
        covered_or_uncovered: Option<CoveredOrUncovered>,
        customer_or_firm: Option<CustomerOrFirm>,
        max_show: Option<FIXInt>,
        locate_reqd: Option<LocateReqd>
    },

    /// OrderStatusRequest message. Message code: H
    OrderStatusRequest {
        order_id: Option<FIXString>,
        cl_ord_id: FIXString,
        client_id: Option<FIXString>,
        exec_broker: Option<FIXString>,
        symbol: FIXString,
        symbol_sfx: Option<FIXString>,
        security_id: Option<FIXString>,
        id_source: Option<IDSource>,
        security_type: Option<SecurityType>,
        maturity_month_year: Option<MonthYear>,
        maturity_day: Option<DayOfMonth>,
        put_or_call: Option<PutOrCall>,
        strike_price: Option<FIXFloat>,
        opt_attribute: Option<FIXString>,
        security_exchange: Option<FIXString>,
        issuer: Option<FIXString>,
        security_desc: Option<FIXString>,
        side: Side
    },

    /// Allocation message. Message code: J
    Allocation {
        alloc_id: FIXString,
        alloc_trans_type: AllocTransType,
        ref_alloc_id: Option<FIXString>,
        alloc_link_id: Option<FIXString>,
        alloc_link_type: Option<AllocLinkType>,
        cl_ord_id: Option<FIXString>,
        order_id: Option<FIXString>,
        secondary_order_id: Option<FIXString>,
        list_id: Option<FIXString>,
        wave_no: Option<FIXString>,
        last_shares: Option<FIXInt>,
        exec_id: Option<FIXString>,
        last_px: Option<FIXFloat>,
        last_capacity: Option<LastCapacity>,
        side: Side,
        symbol: FIXString,
        symbol_sfx: Option<FIXString>,
        security_id: Option<FIXString>,
        id_source: Option<IDSource>,
        security_type: Option<SecurityType>,
        maturity_month_year: Option<MonthYear>,
        maturity_day: Option<DayOfMonth>,
        put_or_call: Option<PutOrCall>,
        strike_price: Option<FIXFloat>,
        opt_attribute: Option<FIXString>,
        security_exchange: Option<FIXString>,
        issuer: Option<FIXString>,
        security_desc: Option<FIXString>,
        shares: FIXInt,
        last_mkt: Option<FIXString>,
        avg_px: FIXFloat,
        currency: Option<FIXString>,
        avg_prx_precision: Option<FIXInt>,
        trade_date: UTCDateOnly,
        transact_time: Option<UTCTimeOnly>,
        settlmnt_typ: Option<SettlmntTyp>,
        fut_sett_date: Option<UTCDateOnly>,
        net_money: Option<FIXFloat>,
        open_close: Option<OpenClose>,
        text: Option<FIXString>,
        num_days_interest: Option<FIXInt>,
        accrued_interest_rate: Option<FIXFloat>,
        alloc_account: Option<FIXString>,
        alloc_shares: FIXInt,
        process_code: Option<ProcessCode>,
        broker_of_credit: Option<FIXString>,
        notify_broker_of_credit: Option<NotifyBrokerOfCredit>,
        alloc_handl_inst: Option<AllocHandlInst>,
        alloc_text: Option<FIXString>,
        exec_broker: Option<FIXString>,
        client_id: Option<FIXString>,
        commission: Option<FIXFloat>,
        comm_type: Option<CommType>,
        alloc_avg_px: Option<FIXFloat>,
        alloc_net_money: Option<FIXFloat>,
        settl_curr_amt: Option<FIXFloat>,
        settl_currency: Option<FIXString>,
        settl_curr_fx_rate: Option<FIXFloat>,
        settl_curr_fx_rate_calc: Option<SettlCurrFxRateCalc>,
        accrued_interest_amt: Option<FIXFloat>,
        settl_inst_mode: Option<SettlInstMode>,
        misc_fee_amt: Option<FIXFloat>,
        misc_fee_curr: Option<FIXString>,
        misc_fee_type: Option<MiscFeeType>
    },

    /// ListCancelRequest message. Message code: K
    ListCancelRequest {
        list_id: FIXString,
        wave_no: Option<FIXString>,
        text: Option<FIXString>
    },

    /// ListExecute message. Message code: L
    ListExecute {
        list_id: FIXString,
        wave_no: Option<FIXString>,
        text: Option<FIXString>
    },

    /// ListStatusRequest message. Message code: M
    ListStatusRequest {
        list_id: FIXString,
        wave_no: Option<FIXString>,
        text: Option<FIXString>
    },

    /// ListStatus message. Message code: N
    ListStatus {
        list_id: FIXString,
        wave_no: Option<FIXString>,
        no_rpts: FIXInt,
        rpt_seq: FIXInt,
        cl_ord_id: FIXString,
        cum_qty: FIXInt,
        leaves_qty: FIXInt,
        cxl_qty: FIXInt,
        avg_px: FIXFloat
    },

    /// AllocationInstructionAck message. Message code: P
    AllocationInstructionAck {
        client_id: Option<FIXString>,
        exec_broker: Option<FIXString>,
        alloc_id: FIXString,
        trade_date: UTCDateOnly,
        transact_time: Option<UTCTimeOnly>,
        alloc_status: AllocStatus,
        alloc_rej_code: Option<AllocRejCode>,
        text: Option<FIXString>
    },

    /// DontKnowTrade message. Message code: Q
    DontKnowTrade {
        order_id: Option<FIXString>,
        exec_id: Option<FIXString>,
        dk_reason: DKReason,
        symbol: FIXString,
        symbol_sfx: Option<FIXString>,
        security_id: Option<FIXString>,
        id_source: Option<IDSource>,
        security_type: Option<SecurityType>,
        maturity_month_year: Option<MonthYear>,
        maturity_day: Option<DayOfMonth>,
        put_or_call: Option<PutOrCall>,
        strike_price: Option<FIXFloat>,
        opt_attribute: Option<FIXString>,
        security_exchange: Option<FIXString>,
        issuer: Option<FIXString>,
        security_desc: Option<FIXString>,
        side: Side,
        order_qty: Option<FIXInt>,
        cash_order_qty: Option<FIXFloat>,
        last_shares: Option<FIXInt>,
        last_px: Option<FIXFloat>,
        text: Option<FIXString>
    },

    /// QuoteRequest message. Message code: R
    QuoteRequest {
        quote_req_id: FIXString,
        symbol: FIXString,
        symbol_sfx: Option<FIXString>,
        security_id: Option<FIXString>,
        id_source: Option<IDSource>,
        security_type: Option<SecurityType>,
        maturity_month_year: Option<MonthYear>,
        maturity_day: Option<DayOfMonth>,
        put_or_call: Option<PutOrCall>,
        strike_price: Option<FIXFloat>,
        opt_attribute: Option<FIXString>,
        security_exchange: Option<FIXString>,
        issuer: Option<FIXString>,
        security_desc: Option<FIXString>,
        prev_close_px: Option<FIXFloat>,
        side: Option<Side>,
        order_qty: Option<FIXInt>,
        fut_sett_date: Option<UTCDateOnly>,
        ord_type: Option<OrdType>,
        fut_sett_date2: Option<UTCDateOnly>,
        order_qty2: Option<FIXFloat>
    },

    /// Quote message. Message code: S
    Quote {
        quote_req_id: Option<FIXString>,
        quote_id: FIXString,
        symbol: FIXString,
        symbol_sfx: Option<FIXString>,
        security_id: Option<FIXString>,
        id_source: Option<IDSource>,
        security_type: Option<SecurityType>,
        maturity_month_year: Option<MonthYear>,
        maturity_day: Option<DayOfMonth>,
        put_or_call: Option<PutOrCall>,
        strike_price: Option<FIXFloat>,
        opt_attribute: Option<FIXString>,
        security_exchange: Option<FIXString>,
        issuer: Option<FIXString>,
        security_desc: Option<FIXString>,
        bid_px: Option<FIXFloat>,
        offer_px: Option<FIXFloat>,
        bid_size: Option<FIXInt>,
        offer_size: Option<FIXInt>,
        valid_until_time: Option<UTCTimeOnly>,
        bid_spot_rate: Option<FIXFloat>,
        offer_spot_rate: Option<FIXFloat>,
        bid_forward_points: Option<FIXFloat>,
        offer_forward_points: Option<FIXFloat>,
        transact_time: Option<UTCTimeOnly>,
        fut_sett_date: Option<UTCDateOnly>,
        ord_type: Option<OrdType>,
        fut_sett_date2: Option<UTCDateOnly>,
        order_qty2: Option<FIXFloat>
    },

    /// SettlementInstructions message. Message code: T
    SettlementInstructions {
        settl_inst_id: FIXString,
        settl_inst_trans_type: SettlInstTransType,
        settl_inst_mode: SettlInstMode,
        settl_inst_source: SettlInstSource,
        alloc_account: FIXString,
        settl_location: Option<SettlLocation>,
        trade_date: Option<UTCDateOnly>,
        alloc_id: Option<FIXString>,
        last_mkt: Option<FIXString>,
        side: Option<Side>,
        security_type: Option<SecurityType>,
        effective_time: Option<UTCTimeOnly>,
        transact_time: UTCTimeOnly,
        client_id: Option<FIXString>,
        exec_broker: Option<FIXString>,
        stand_inst_db_type: Option<StandInstDbType>,
        stand_inst_db_name: Option<FIXString>,
        stand_inst_db_id: Option<FIXString>,
        settl_delivery_type: Option<FIXInt>,
        settl_depository_code: Option<FIXString>,
        settl_brkr_code: Option<FIXString>,
        settl_inst_code: Option<FIXString>,
        security_settl_agent_name: Option<FIXString>,
        security_settl_agent_code: Option<FIXString>,
        security_settl_agent_acct_num: Option<FIXString>,
        security_settl_agent_acct_name: Option<FIXString>,
        security_settl_agent_contact_name: Option<FIXString>,
        security_settl_agent_contact_phone: Option<FIXString>,
        cash_settl_agent_name: Option<FIXString>,
        cash_settl_agent_code: Option<FIXString>,
        cash_settl_agent_acct_num: Option<FIXString>,
        cash_settl_agent_acct_name: Option<FIXString>,
        cash_settl_agent_contact_name: Option<FIXString>,
        cash_settl_agent_contact_phone: Option<FIXString>
    }
}