use types::*;
use fix41::fields::*;

pub struct Header {
    pub begin_string: FIXChar,
    pub body_length: FIXInt,
    pub msg_type: MsgType,
    pub sender_comp_id: FIXChar,
    pub target_comp_id: FIXChar,
    pub on_behalf_of_comp_id: Option<FIXChar>,
    pub deliver_to_comp_id: Option<FIXChar>,
    pub secure_data_len: Option<Length>,
    pub secure_data: Option<Data>,
    pub msg_seq_num: FIXInt,
    pub sender_sub_id: Option<FIXChar>,
    pub sender_location_id: Option<FIXChar>,
    pub target_sub_id: Option<FIXChar>,
    pub target_location_id: Option<FIXChar>,
    pub on_behalf_of_sub_id: Option<FIXChar>,
    pub on_behalf_of_location_id: Option<FIXChar>,
    pub deliver_to_sub_id: Option<FIXChar>,
    pub deliver_to_location_id: Option<FIXChar>,
    pub poss_dup_flag: Option<PossDupFlag>,
    pub poss_resend: Option<PossResend>,
    pub sending_time: UTCTimeOnly,
    pub orig_sending_time: Option<UTCTimeOnly>
}

pub struct Trailer {
    pub begin_string: FIXChar,
    pub body_length: FIXInt,
    pub msg_type: MsgType,
    pub sender_comp_id: FIXChar,
    pub target_comp_id: FIXChar,
    pub on_behalf_of_comp_id: Option<FIXChar>,
    pub deliver_to_comp_id: Option<FIXChar>,
    pub secure_data_len: Option<Length>,
    pub secure_data: Option<Data>,
    pub msg_seq_num: FIXInt,
    pub sender_sub_id: Option<FIXChar>,
    pub sender_location_id: Option<FIXChar>,
    pub target_sub_id: Option<FIXChar>,
    pub target_location_id: Option<FIXChar>,
    pub on_behalf_of_sub_id: Option<FIXChar>,
    pub on_behalf_of_location_id: Option<FIXChar>,
    pub deliver_to_sub_id: Option<FIXChar>,
    pub deliver_to_location_id: Option<FIXChar>,
    pub poss_dup_flag: Option<PossDupFlag>,
    pub poss_resend: Option<PossResend>,
    pub sending_time: UTCTimeOnly,
    pub orig_sending_time: Option<UTCTimeOnly>
}

pub struct Message {
    pub header: Header,
    pub trailer: Trailer,
    pub body: MessageBody
}

pub enum MessageBody {
    Heartbeat {
        test_req_id: Option<FIXChar>
    },
    TestRequest {
        test_req_id: FIXChar
    },
    ResendRequest {
        begin_seq_no: FIXInt,
        end_seq_no: FIXInt
    },
    Reject {
        ref_seq_num: FIXInt,
        text: Option<FIXChar>
    },
    SequenceReset {
        gap_fill_flag: Option<GapFillFlag>,
        new_seq_no: FIXInt
    },
    Logout {
        text: Option<FIXChar>
    },
    IOI {
        io_iid: FIXChar,
        ioi_trans_type: IOITransType,
        ioi_ref_id: Option<FIXChar>,
        symbol: FIXChar,
        symbol_sfx: Option<FIXChar>,
        security_id: Option<FIXChar>,
        id_source: Option<IDSource>,
        security_type: Option<SecurityType>,
        maturity_month_year: Option<MonthYear>,
        maturity_day: Option<DayOfMonth>,
        put_or_call: Option<PutOrCall>,
        strike_price: Option<FIXFloat>,
        opt_attribute: Option<FIXChar>,
        security_exchange: Option<FIXChar>,
        issuer: Option<FIXChar>,
        security_desc: Option<FIXChar>,
        side: Side,
        ioi_shares: IOIShares,
        price: Option<FIXFloat>,
        currency: Option<FIXChar>,
        valid_until_time: Option<UTCTimeOnly>,
        ioi_qlty_ind: Option<IOIQltyInd>,
        ioi_oth_svc: Option<IOIOthSvc>,
        ioi_natural_flag: Option<IOINaturalFlag>,
        no_ioi_qualifiers: Option<FIXInt>,
        text: Option<FIXChar>,
        transact_time: Option<UTCTimeOnly>,
        url_link: Option<FIXChar>
    },
    Advertisement {
        adv_id: FIXChar,
        adv_trans_type: AdvTransType,
        adv_ref_id: Option<FIXChar>,
        symbol: FIXChar,
        symbol_sfx: Option<FIXChar>,
        security_id: Option<FIXChar>,
        id_source: Option<IDSource>,
        security_type: Option<SecurityType>,
        maturity_month_year: Option<MonthYear>,
        maturity_day: Option<DayOfMonth>,
        put_or_call: Option<PutOrCall>,
        strike_price: Option<FIXFloat>,
        opt_attribute: Option<FIXChar>,
        security_exchange: Option<FIXChar>,
        issuer: Option<FIXChar>,
        security_desc: Option<FIXChar>,
        adv_side: AdvSide,
        shares: FIXInt,
        price: Option<FIXFloat>,
        currency: Option<FIXChar>,
        trade_date: Option<UTCDateOnly>,
        transact_time: Option<UTCTimeOnly>,
        text: Option<FIXChar>,
        url_link: Option<FIXChar>,
        last_mkt: Option<FIXChar>
    },
    ExecutionReport {
        order_id: FIXChar,
        secondary_order_id: Option<FIXChar>,
        cl_ord_id: Option<FIXChar>,
        orig_cl_ord_id: Option<FIXChar>,
        client_id: Option<FIXChar>,
        exec_broker: Option<FIXChar>,
        list_id: Option<FIXChar>,
        exec_id: FIXChar,
        exec_trans_type: ExecTransType,
        exec_ref_id: Option<FIXChar>,
        exec_type: ExecType,
        ord_status: OrdStatus,
        ord_rej_reason: Option<OrdRejReason>,
        account: Option<FIXChar>,
        settlmnt_typ: Option<SettlmntTyp>,
        fut_sett_date: Option<UTCDateOnly>,
        symbol: FIXChar,
        symbol_sfx: Option<FIXChar>,
        security_id: Option<FIXChar>,
        id_source: Option<IDSource>,
        security_type: Option<SecurityType>,
        maturity_month_year: Option<MonthYear>,
        maturity_day: Option<DayOfMonth>,
        put_or_call: Option<PutOrCall>,
        strike_price: Option<FIXFloat>,
        opt_attribute: Option<FIXChar>,
        security_exchange: Option<FIXChar>,
        issuer: Option<FIXChar>,
        security_desc: Option<FIXChar>,
        side: Side,
        order_qty: FIXInt,
        ord_type: Option<OrdType>,
        price: Option<FIXFloat>,
        stop_px: Option<FIXFloat>,
        peg_difference: Option<FIXFloat>,
        currency: Option<FIXChar>,
        time_in_force: Option<TimeInForce>,
        expire_time: Option<UTCTimeOnly>,
        exec_inst: Option<ExecInst>,
        rule80_a: Option<Rule80A>,
        last_shares: FIXInt,
        last_px: FIXFloat,
        last_spot_rate: Option<FIXFloat>,
        last_forward_points: Option<FIXFloat>,
        last_mkt: Option<FIXChar>,
        last_capacity: Option<LastCapacity>,
        leaves_qty: FIXInt,
        cum_qty: FIXInt,
        avg_px: FIXFloat,
        trade_date: Option<UTCDateOnly>,
        transact_time: Option<UTCTimeOnly>,
        report_to_exch: Option<ReportToExch>,
        commission: Option<FIXFloat>,
        comm_type: Option<CommType>,
        settl_curr_amt: Option<FIXFloat>,
        settl_currency: Option<FIXChar>,
        settl_curr_fx_rate: Option<FIXFloat>,
        settl_curr_fx_rate_calc: Option<SettlCurrFxRateCalc>,
        text: Option<FIXChar>
    },
    OrderCancelReject {
        order_id: FIXChar,
        secondary_order_id: Option<FIXChar>,
        cl_ord_id: FIXChar,
        orig_cl_ord_id: FIXChar,
        ord_status: OrdStatus,
        client_id: Option<FIXChar>,
        exec_broker: Option<FIXChar>,
        list_id: Option<FIXChar>,
        cxl_rej_reason: Option<CxlRejReason>,
        text: Option<FIXChar>
    },
    Logon {
        encrypt_method: EncryptMethod,
        heart_bt_int: FIXInt,
        raw_data_length: Option<Length>,
        raw_data: Option<Data>,
        reset_seq_num_flag: Option<ResetSeqNumFlag>
    },
    News {
        orig_time: Option<UTCTimeOnly>,
        urgency: Option<Urgency>,
        headline: FIXChar,
        no_related_sym: Option<FIXInt>,
        lines_of_text: FIXInt,
        url_link: Option<FIXChar>,
        raw_data_length: Option<Length>,
        raw_data: Option<Data>
    },
    Email {
        email_thread_id: FIXChar,
        email_type: EmailType,
        orig_time: Option<UTCTimeOnly>,
        subject: FIXChar,
        no_related_sym: Option<FIXInt>,
        order_id: Option<FIXChar>,
        cl_ord_id: Option<FIXChar>,
        lines_of_text: FIXInt,
        raw_data_length: Option<Length>,
        raw_data: Option<Data>
    },
    NewOrderSingle {
        cl_ord_id: FIXChar,
        client_id: Option<FIXChar>,
        exec_broker: Option<FIXChar>,
        account: Option<FIXChar>,
        settlmnt_typ: Option<SettlmntTyp>,
        fut_sett_date: Option<UTCDateOnly>,
        handl_inst: HandlInst,
        exec_inst: Option<ExecInst>,
        min_qty: Option<FIXInt>,
        max_floor: Option<FIXInt>,
        ex_destination: Option<FIXChar>,
        process_code: Option<ProcessCode>,
        symbol: FIXChar,
        symbol_sfx: Option<FIXChar>,
        security_id: Option<FIXChar>,
        id_source: Option<IDSource>,
        security_type: Option<SecurityType>,
        maturity_month_year: Option<MonthYear>,
        maturity_day: Option<DayOfMonth>,
        put_or_call: Option<PutOrCall>,
        strike_price: Option<FIXFloat>,
        opt_attribute: Option<FIXChar>,
        security_exchange: Option<FIXChar>,
        issuer: Option<FIXChar>,
        security_desc: Option<FIXChar>,
        prev_close_px: Option<FIXFloat>,
        side: Side,
        locate_reqd: Option<LocateReqd>,
        order_qty: Option<FIXInt>,
        cash_order_qty: Option<FIXFloat>,
        ord_type: OrdType,
        price: Option<FIXFloat>,
        stop_px: Option<FIXFloat>,
        currency: Option<FIXChar>,
        io_iid: Option<FIXChar>,
        quote_id: Option<FIXChar>,
        time_in_force: Option<TimeInForce>,
        expire_time: Option<UTCTimeOnly>,
        commission: Option<FIXFloat>,
        comm_type: Option<CommType>,
        rule80_a: Option<Rule80A>,
        forex_req: Option<ForexReq>,
        settl_currency: Option<FIXChar>,
        text: Option<FIXChar>,
        fut_sett_date2: Option<UTCDateOnly>,
        order_qty2: Option<FIXFloat>,
        open_close: Option<OpenClose>,
        covered_or_uncovered: Option<CoveredOrUncovered>,
        customer_or_firm: Option<CustomerOrFirm>,
        max_show: Option<FIXInt>,
        peg_difference: Option<FIXFloat>
    },
    NewOrderList {
        list_id: FIXChar,
        wave_no: Option<FIXChar>,
        list_seq_no: FIXInt,
        list_no_ords: FIXInt,
        list_exec_inst: Option<FIXChar>,
        cl_ord_id: FIXChar,
        client_id: Option<FIXChar>,
        exec_broker: Option<FIXChar>,
        account: Option<FIXChar>,
        settlmnt_typ: Option<SettlmntTyp>,
        fut_sett_date: Option<UTCDateOnly>,
        handl_inst: HandlInst,
        exec_inst: Option<ExecInst>,
        min_qty: Option<FIXInt>,
        max_floor: Option<FIXInt>,
        ex_destination: Option<FIXChar>,
        process_code: Option<ProcessCode>,
        symbol: FIXChar,
        symbol_sfx: Option<FIXChar>,
        security_id: Option<FIXChar>,
        id_source: Option<IDSource>,
        security_type: Option<SecurityType>,
        maturity_month_year: Option<MonthYear>,
        maturity_day: Option<DayOfMonth>,
        put_or_call: Option<PutOrCall>,
        strike_price: Option<FIXFloat>,
        opt_attribute: Option<FIXChar>,
        security_exchange: Option<FIXChar>,
        issuer: Option<FIXChar>,
        security_desc: Option<FIXChar>,
        prev_close_px: Option<FIXFloat>,
        side: Side,
        locate_reqd: Option<LocateReqd>,
        order_qty: FIXInt,
        ord_type: OrdType,
        price: Option<FIXFloat>,
        stop_px: Option<FIXFloat>,
        peg_difference: Option<FIXFloat>,
        currency: Option<FIXChar>,
        time_in_force: Option<TimeInForce>,
        expire_time: Option<UTCTimeOnly>,
        commission: Option<FIXFloat>,
        comm_type: Option<CommType>,
        rule80_a: Option<Rule80A>,
        forex_req: Option<ForexReq>,
        settl_currency: Option<FIXChar>,
        text: Option<FIXChar>,
        fut_sett_date2: Option<UTCDateOnly>,
        order_qty2: Option<FIXFloat>,
        open_close: Option<OpenClose>,
        covered_or_uncovered: Option<CoveredOrUncovered>,
        customer_or_firm: Option<CustomerOrFirm>,
        max_show: Option<FIXInt>
    },
    OrderCancelRequest {
        orig_cl_ord_id: FIXChar,
        order_id: Option<FIXChar>,
        cl_ord_id: FIXChar,
        list_id: Option<FIXChar>,
        client_id: Option<FIXChar>,
        exec_broker: Option<FIXChar>,
        symbol: FIXChar,
        symbol_sfx: Option<FIXChar>,
        security_id: Option<FIXChar>,
        id_source: Option<IDSource>,
        security_type: Option<SecurityType>,
        maturity_month_year: Option<MonthYear>,
        maturity_day: Option<DayOfMonth>,
        put_or_call: Option<PutOrCall>,
        strike_price: Option<FIXFloat>,
        opt_attribute: Option<FIXChar>,
        security_exchange: Option<FIXChar>,
        issuer: Option<FIXChar>,
        security_desc: Option<FIXChar>,
        side: Side,
        order_qty: Option<FIXInt>,
        cash_order_qty: Option<FIXFloat>,
        text: Option<FIXChar>
    },
    OrderCancelReplaceRequest {
        order_id: Option<FIXChar>,
        client_id: Option<FIXChar>,
        exec_broker: Option<FIXChar>,
        orig_cl_ord_id: FIXChar,
        cl_ord_id: FIXChar,
        list_id: Option<FIXChar>,
        account: Option<FIXChar>,
        settlmnt_typ: Option<SettlmntTyp>,
        fut_sett_date: Option<UTCDateOnly>,
        handl_inst: HandlInst,
        exec_inst: Option<ExecInst>,
        min_qty: Option<FIXInt>,
        max_floor: Option<FIXInt>,
        ex_destination: Option<FIXChar>,
        symbol: FIXChar,
        symbol_sfx: Option<FIXChar>,
        security_id: Option<FIXChar>,
        id_source: Option<IDSource>,
        security_type: Option<SecurityType>,
        maturity_month_year: Option<MonthYear>,
        maturity_day: Option<DayOfMonth>,
        put_or_call: Option<PutOrCall>,
        strike_price: Option<FIXFloat>,
        opt_attribute: Option<FIXChar>,
        security_exchange: Option<FIXChar>,
        issuer: Option<FIXChar>,
        security_desc: Option<FIXChar>,
        side: Side,
        order_qty: Option<FIXInt>,
        cash_order_qty: Option<FIXFloat>,
        ord_type: OrdType,
        price: Option<FIXFloat>,
        stop_px: Option<FIXFloat>,
        peg_difference: Option<FIXFloat>,
        currency: Option<FIXChar>,
        time_in_force: Option<TimeInForce>,
        expire_time: Option<UTCTimeOnly>,
        commission: Option<FIXFloat>,
        comm_type: Option<CommType>,
        rule80_a: Option<Rule80A>,
        forex_req: Option<ForexReq>,
        settl_currency: Option<FIXChar>,
        text: Option<FIXChar>,
        fut_sett_date2: Option<UTCDateOnly>,
        order_qty2: Option<FIXFloat>,
        open_close: Option<OpenClose>,
        covered_or_uncovered: Option<CoveredOrUncovered>,
        customer_or_firm: Option<CustomerOrFirm>,
        max_show: Option<FIXInt>,
        locate_reqd: Option<LocateReqd>
    },
    OrderStatusRequest {
        order_id: Option<FIXChar>,
        cl_ord_id: FIXChar,
        client_id: Option<FIXChar>,
        exec_broker: Option<FIXChar>,
        symbol: FIXChar,
        symbol_sfx: Option<FIXChar>,
        security_id: Option<FIXChar>,
        id_source: Option<IDSource>,
        security_type: Option<SecurityType>,
        maturity_month_year: Option<MonthYear>,
        maturity_day: Option<DayOfMonth>,
        put_or_call: Option<PutOrCall>,
        strike_price: Option<FIXFloat>,
        opt_attribute: Option<FIXChar>,
        security_exchange: Option<FIXChar>,
        issuer: Option<FIXChar>,
        security_desc: Option<FIXChar>,
        side: Side
    },
    Allocation {
        alloc_id: FIXChar,
        alloc_trans_type: AllocTransType,
        ref_alloc_id: Option<FIXChar>,
        alloc_link_id: Option<FIXChar>,
        alloc_link_type: Option<AllocLinkType>,
        no_orders: Option<FIXInt>,
        no_execs: Option<FIXInt>,
        side: Side,
        symbol: FIXChar,
        symbol_sfx: Option<FIXChar>,
        security_id: Option<FIXChar>,
        id_source: Option<IDSource>,
        security_type: Option<SecurityType>,
        maturity_month_year: Option<MonthYear>,
        maturity_day: Option<DayOfMonth>,
        put_or_call: Option<PutOrCall>,
        strike_price: Option<FIXFloat>,
        opt_attribute: Option<FIXChar>,
        security_exchange: Option<FIXChar>,
        issuer: Option<FIXChar>,
        security_desc: Option<FIXChar>,
        shares: FIXInt,
        last_mkt: Option<FIXChar>,
        avg_px: FIXFloat,
        currency: Option<FIXChar>,
        avg_prx_precision: Option<FIXInt>,
        trade_date: UTCDateOnly,
        transact_time: Option<UTCTimeOnly>,
        settlmnt_typ: Option<SettlmntTyp>,
        fut_sett_date: Option<UTCDateOnly>,
        net_money: Option<FIXFloat>,
        open_close: Option<OpenClose>,
        text: Option<FIXChar>,
        num_days_interest: Option<FIXInt>,
        accrued_interest_rate: Option<FIXFloat>,
        no_allocs: Option<FIXInt>
    },
    ListCancelRequest {
        list_id: FIXChar,
        wave_no: Option<FIXChar>,
        text: Option<FIXChar>
    },
    ListExecute {
        list_id: FIXChar,
        wave_no: Option<FIXChar>,
        text: Option<FIXChar>
    },
    ListStatusRequest {
        list_id: FIXChar,
        wave_no: Option<FIXChar>,
        text: Option<FIXChar>
    },
    ListStatus {
        list_id: FIXChar,
        wave_no: Option<FIXChar>,
        no_rpts: FIXInt,
        rpt_seq: FIXInt,
        no_orders: FIXInt
    },
    AllocationInstructionAck {
        client_id: Option<FIXChar>,
        exec_broker: Option<FIXChar>,
        alloc_id: FIXChar,
        trade_date: UTCDateOnly,
        transact_time: Option<UTCTimeOnly>,
        alloc_status: AllocStatus,
        alloc_rej_code: Option<AllocRejCode>,
        text: Option<FIXChar>
    },
    DontKnowTrade {
        order_id: Option<FIXChar>,
        exec_id: Option<FIXChar>,
        dk_reason: DKReason,
        symbol: FIXChar,
        symbol_sfx: Option<FIXChar>,
        security_id: Option<FIXChar>,
        id_source: Option<IDSource>,
        security_type: Option<SecurityType>,
        maturity_month_year: Option<MonthYear>,
        maturity_day: Option<DayOfMonth>,
        put_or_call: Option<PutOrCall>,
        strike_price: Option<FIXFloat>,
        opt_attribute: Option<FIXChar>,
        security_exchange: Option<FIXChar>,
        issuer: Option<FIXChar>,
        security_desc: Option<FIXChar>,
        side: Side,
        order_qty: Option<FIXInt>,
        cash_order_qty: Option<FIXFloat>,
        last_shares: Option<FIXInt>,
        last_px: Option<FIXFloat>,
        text: Option<FIXChar>
    },
    QuoteRequest {
        quote_req_id: FIXChar,
        symbol: FIXChar,
        symbol_sfx: Option<FIXChar>,
        security_id: Option<FIXChar>,
        id_source: Option<IDSource>,
        security_type: Option<SecurityType>,
        maturity_month_year: Option<MonthYear>,
        maturity_day: Option<DayOfMonth>,
        put_or_call: Option<PutOrCall>,
        strike_price: Option<FIXFloat>,
        opt_attribute: Option<FIXChar>,
        security_exchange: Option<FIXChar>,
        issuer: Option<FIXChar>,
        security_desc: Option<FIXChar>,
        prev_close_px: Option<FIXFloat>,
        side: Option<Side>,
        order_qty: Option<FIXInt>,
        fut_sett_date: Option<UTCDateOnly>,
        ord_type: Option<OrdType>,
        fut_sett_date2: Option<UTCDateOnly>,
        order_qty2: Option<FIXFloat>
    },
    Quote {
        quote_req_id: Option<FIXChar>,
        quote_id: FIXChar,
        symbol: FIXChar,
        symbol_sfx: Option<FIXChar>,
        security_id: Option<FIXChar>,
        id_source: Option<IDSource>,
        security_type: Option<SecurityType>,
        maturity_month_year: Option<MonthYear>,
        maturity_day: Option<DayOfMonth>,
        put_or_call: Option<PutOrCall>,
        strike_price: Option<FIXFloat>,
        opt_attribute: Option<FIXChar>,
        security_exchange: Option<FIXChar>,
        issuer: Option<FIXChar>,
        security_desc: Option<FIXChar>,
        bid_px: Option<FIXFloat>,
        offer_px: Option<FIXFloat>,
        bid_size: Option<FIXInt>,
        offer_size: Option<FIXInt>,
        valid_until_time: Option<UTCTimeOnly>,
        bid_spot_rate: Option<FIXFloat>,
        offer_spot_rate: Option<FIXFloat>,
        bid_forward_points: Option<FIXFloat>,
        offer_forward_points: Option<FIXFloat>,
        transact_time: Option<UTCTimeOnly>,
        fut_sett_date: Option<UTCDateOnly>,
        ord_type: Option<OrdType>,
        fut_sett_date2: Option<UTCDateOnly>,
        order_qty2: Option<FIXFloat>
    },
    SettlementInstructions {
        settl_inst_id: FIXChar,
        settl_inst_trans_type: SettlInstTransType,
        settl_inst_mode: SettlInstMode,
        settl_inst_source: SettlInstSource,
        alloc_account: FIXChar,
        settl_location: Option<SettlLocation>,
        trade_date: Option<UTCDateOnly>,
        alloc_id: Option<FIXChar>,
        last_mkt: Option<FIXChar>,
        side: Option<Side>,
        security_type: Option<SecurityType>,
        effective_time: Option<UTCTimeOnly>,
        transact_time: UTCTimeOnly,
        client_id: Option<FIXChar>,
        exec_broker: Option<FIXChar>,
        stand_inst_db_type: Option<StandInstDbType>,
        stand_inst_db_name: Option<FIXChar>,
        stand_inst_db_id: Option<FIXChar>,
        settl_delivery_type: Option<FIXInt>,
        settl_depository_code: Option<FIXChar>,
        settl_brkr_code: Option<FIXChar>,
        settl_inst_code: Option<FIXChar>,
        security_settl_agent_name: Option<FIXChar>,
        security_settl_agent_code: Option<FIXChar>,
        security_settl_agent_acct_num: Option<FIXChar>,
        security_settl_agent_acct_name: Option<FIXChar>,
        security_settl_agent_contact_name: Option<FIXChar>,
        security_settl_agent_contact_phone: Option<FIXChar>,
        cash_settl_agent_name: Option<FIXChar>,
        cash_settl_agent_code: Option<FIXChar>,
        cash_settl_agent_acct_num: Option<FIXChar>,
        cash_settl_agent_acct_name: Option<FIXChar>,
        cash_settl_agent_contact_name: Option<FIXChar>,
        cash_settl_agent_contact_phone: Option<FIXChar>
    }
}